language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6

before_install:
- pip install -U pip setuptools wheel tox-travis
- pip install twine

branches:
  only:
  - master
  - '/^v?\d(\.\d+)+$/'

script:
- python setup.py sdist
- python setup.py bdist_wheel
- twine check dist/*
- tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  user: __token__
  password:
    secure: PLEASE_REPLACE_ME
  on:
    repo: dldevinc/paper-forms
    condition: $TRAVIS_PYTHON_VERSION = 3.8
    tags: true
